"""Enumerations with stable serialized values."""

from enum import StrEnum


class AccountMode(StrEnum):
    DEMO = "demo"
    REAL = "real"
    UNKNOWN = "unknown"


class Direction(StrEnum):
    LONG = "long"
    SHORT = "short"


class EventImportance(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class EventStatus(StrEnum):
    SCHEDULED = "scheduled"
    CANCELLED = "cancelled"
    AMBIGUOUS = "ambiguous"
    DUPLICATE = "duplicate"
    STALE = "stale"


class SystemState(StrEnum):
    SLEEPING = "sleeping"
    ARMED = "armed"
    SHOCK_WINDOW = "shock_window"
    WAITING_RETEST = "waiting_retest"
    READY = "ready"
    IN_POSITION = "in_position"
    EXPIRED = "expired"
    LOCKED = "locked"
    DISARMED = "disarmed"


class ReasonCode(StrEnum):
    CATALYST_PASS = "CATALYST_PASS"
    EVENT_NOT_HIGH_IMPORTANCE = "EVENT_NOT_HIGH_IMPORTANCE"
    EVENT_NOT_ELIGIBLE = "EVENT_NOT_ELIGIBLE"
    SYMBOL_NOT_MAPPED = "SYMBOL_NOT_MAPPED"
    SHOCK_WINDOW_ACTIVE = "SHOCK_WINDOW_ACTIVE"
    ENTRY_WINDOW_EXPIRED = "ENTRY_WINDOW_EXPIRED"
    ACCEPTANCE_PASS = "ACCEPTANCE_PASS"
    PRICE_INSIDE_RANGE = "PRICE_INSIDE_RANGE"
    RETEST_INVALID = "RETEST_INVALID"
    CONFIRMATION_PASS = "CONFIRMATION_PASS"
    RELATED_MARKETS_MISSING = "RELATED_MARKETS_MISSING"
    CONFIRMATION_INSUFFICIENT = "CONFIRMATION_INSUFFICIENT"
    EXECUTION_PASS = "EXECUTION_PASS"
    MARKET_CLOSED = "MARKET_CLOSED"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    DATA_STALE = "DATA_STALE"
    STOP_INVALID = "STOP_INVALID"
    BROKER_DISCONNECTED = "BROKER_DISCONNECTED"
    ACCOUNT_SNAPSHOT_STALE = "ACCOUNT_SNAPSHOT_STALE"
    DEMO_ONLY = "DEMO_ONLY"
    CLUSTER_LIMIT = "CLUSTER_LIMIT"
    LOSS_STREAK_LOCK = "LOSS_STREAK_LOCK"
    DAILY_LOSS_LOCK = "DAILY_LOSS_LOCK"
    INVALID_RISK = "INVALID_RISK"
    RISK_ALLOWED = "RISK_ALLOWED"
    STATE_DISARMED = "STATE_DISARMED"
    STATE_RISK_LOCKED = "STATE_RISK_LOCKED"
    STATE_IN_POSITION = "STATE_IN_POSITION"
    STATE_SLEEPING = "STATE_SLEEPING"
    STATE_ARMED = "STATE_ARMED"
    STATE_SHOCK_WINDOW = "STATE_SHOCK_WINDOW"
    STATE_EXPIRED = "STATE_EXPIRED"
    STATE_READY = "STATE_READY"
    STATE_WAITING_RETEST = "STATE_WAITING_RETEST"
    SETUP_NOT_READY = "SETUP_NOT_READY"
    NO_DIRECTION = "NO_DIRECTION"
    PLAN_INVALID = "PLAN_INVALID"
    TRADE_PLAN_READY = "TRADE_PLAN_READY"
